version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - selenium-network

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - selenium-network

  selenium:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
    networks:
      - selenium-network
    environment:
      - SE_EVENT_BUS_HOST=selenium  # Ensure selenium container is the event bus host

networks:
  selenium-network:
    driver: bridge
