version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - devops-network

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - devops-network

  selenium:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
    networks:
      - devops-network

networks:
  devops-network:
    driver: bridge
